<a href="https://colab.research.google.com/github/Randasabag/Projet-5-ML/blob/main/P5_USE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import tensorflow as tf
import tensorflow_hub as hub

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as st
from scipy.stats import shapiro
import statsmodels.api as sm
import statsmodels.formula.api as smf
from datetime import datetime,date,timedelta
import datetime as dt
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [23]:
df_net=pd.read_csv('/content/drive/MyDrive/MACHINE_LEARNING/df_net.csv', sep=',')
df_net

,LastActivityDate,Title,Tags,Score,sentence_bow,sentence_bow_lem,sentence_dl
0,2022-08-29 20:14:36,Determine the type of an object?,<python><dictionary><types><typeof>,2164,determine type object,determine type object,determine the type of an object ?
1,2022-07-02 05:29:08,Why can't Python parse this JSON data?,<python><json><parsing>,1503,why python parse json data,why python parse json data,why can t python parse this json data ?
2,2023-11-20 22:23:13,Best way to convert string to bytes in Python 3?,<python><string><character-encoding><python-3.x>,1482,best way convert string bytes python,best way convert string byte python,best way to convert string to bytes in python 3 ?
3,2022-11-09 15:44:56,Display number with leading zeros,<python><integer><string-formatting>,1419,display number leading zeros,display number leading zero,display number with leading zeros
4,2023-07-28 17:04:02,Create a Pandas Dataframe by appending one row...,<python><pandas><dataframe><append>,1399,create pandas dataframe appending one row time,create panda dataframe appending one row time,create a pandas dataframe by appending one row...
5,2022-11-23 08:30:50,Should I use 'has_key()' or 'in' on Python dicts?,<python><dictionary>,1122,should use key python dicts,should use key python dicts,should i use has key ( ) or in on python dicts ?
6,2022-08-15 07:57:04,How to check if type of a variable is string?,<python><string><variables><types>,1051,how check type variable string,how check type variable string,how to check if type of a variable is string ?
7,2023-01-27 10:02:02,Which exception should I raise on bad/illegal ...,<python><exception><arguments>,820,which exception raise bad illegal argument com...,which exception raise bad illegal argument com...,which exception should i raise on bad illegal ...
8,2022-05-31 17:20:40,Using @property versus getters and setters,<python><properties><getter-setter>,798,using property versus getters setters,using property versus getters setter,using property versus getters and setters
9,2023-01-29 17:03:17,"How can I check if a string represents an int,...",<python><string><integer>,733,how check string represents int without using ...,how check string represents int without using ...,how can i check if a string represents an int ...
10,2023-08-23 15:00:24,How can I use pickle to save a dict (or any ot...,<python><dictionary><pickle>,702,how use pickle save dict python object,how use pickle save dict python object,how can i use pickle to save a dict ( or any o...
11,2022-08-28 19:10:16,Getting a map() to return a list in Python 3.x,<python><list><python-3.x><map-function>,645,getting map return list python 3.x,getting map return list python 3.x,getting a map ( ) to return a list in python 3.x
12,2023-11-07 17:49:05,How can I pivot a dataframe?,<python><pandas><group-by><pivot><pivot-table>,625,how pivot dataframe,how pivot dataframe,how can i pivot a dataframe ?
13,2020-01-31 06:45:21,Determine if variable is defined in Python,<python><variables><defined>,553,determine variable defined python,determine variable defined python,determine if variable is defined in python
14,2022-07-05 21:20:38,Reading JSON from a file,<python><json>,550,reading json file,reading json file,reading json from a file
15,2021-03-14 20:21:58,Python Dictionary Comprehension,<python><dictionary><list-comprehension>,525,python dictionary comprehension,python dictionary comprehension,python dictionary comprehension
16,2022-09-03 09:33:18,"Is there a way to perform ""if"" in python's lam...",<python><lambda><conditional-operator>,512,way perform python lambda,way perform python lambda,is there a way to perform `` if '' in python s...
17,2020-02-18 13:06:27,Convert a list of characters into a string,<python><string>,489,convert list characters string,convert list character string,convert a list of characters into a string
18,2023-11-03 07:44:03,"How to add to the PYTHONPATH in Windows, so it...",<python><windows><environment-variables><pytho...,475,how add pythonpath windows finds modules packages,how add pythonpath window find module package,"how to add to the pythonpath in windows , so i..."
19,2023-03-21 08:25:43,How to find list intersection?,<python><arrays><intersection>,447,how find list intersection,how find list intersection,how to find list intersection ?
20,2023-10-13 14:51:45,Redirect stdout to a file in Python?,<python><stdout>,440,redirect stdout file python,redirect stdout file python,redirect stdout to a file in python ?
21,2021-06-25 14:13:28,Store output of subprocess.Popen call in a string,<python><subprocess>,430,store output subprocess.popen call string,store output subprocess.popen call string,store output of subprocess.popen call in a string
22,2022-12-19 12:27:33,"Why does range(start, end) not include end?",<python><range>,426,why range start end include end,why range start end include end,"why does range ( start , end ) not include end ?"
23,2024-03-21 04:06:15,Convert a python dict to a string and back,<python><json><dictionary><serialization>,415,convert python dict string back,convert python dict string back,convert a python dict to a string and back
24,2022-11-02 08:35:13,How do you properly determine the current scri...,<python><path><working-directory>,409,how properly determine current script directory,how properly determine current script directory,how do you properly determine the current scri...
25,2019-04-20 01:29:27,How can I check if a key exists in a dictionary?,<python>,404,how check key exists dictionary,how check key exists dictionary,how can i check if a key exists in a dictionary ?
26,2022-08-06 19:04:52,Double Iteration in List Comprehension,<python><list-comprehension>,402,double iteration list comprehension,double iteration list comprehension,double iteration in list comprehension
27,2022-03-30 14:18:48,What's the difference between `raw_input()` an...,<python><python-3.x><input>,400,what difference raw input input python,what difference raw input input python,what s the difference between ` raw input ( ) ...
28,2022-05-24 08:21:27,NumPy array initialization (fill with identica...,<python><arrays><numpy>,396,numpy array initialization fill identical values,numpy array initialization fill identical value,numpy array initialization ( fill with identic...
29,2021-06-28 09:57:35,Python function global variables?,<python><global-variables>,372,python function global variables,python function global variable,python function global variables ?
30,2022-05-08 17:52:09,Get loop count inside a for-loop,<python><for-loop>,361,get loop count inside loop,get loop count inside loop,get loop count inside a for loop
31,2023-05-14 01:50:26,How do I convert all of the items in a list to...,<python><list><casting>,356,how convert items list floats,how convert item list float,how do i convert all of the items in a list to...
32,2022-12-29 23:24:40,'str' object has no attribute 'decode'. Python...,<python><python-3.x>,352,str object attribute decode python error,str object attribute decode python error,str object has no attribute decode . python 3 ...
33,2022-06-09 08:35:13,Access multiple elements of list knowing their...,<python><python-3.x><list><indexing><element>,343,access multiple elements list knowing index,access multiple element list knowing index,access multiple elements of list knowing their...
34,2022-04-05 10:52:38,Take the content of a list and append it to an...,<python><list>,341,take content list append another list,take content list append another list,take the content of a list and append it to an...
35,2023-02-02 18:17:15,List files ONLY in the current directory,<python>,330,list files only current directory,list file only current directory,list files only in the current directory
36,2023-04-24 15:57:39,"Error ""Import Error: No module named numpy"" on...",<python><python-3.x><numpy><import><scipy>,326,error import error module named numpy windows,error import error module named numpy window,error `` import error : no module named numpy ...
37,2023-12-28 20:34:37,Are nested try/except blocks in Python a good ...,<python>,320,are nested try except blocks python good progr...,are nested try except block python good progra...,are nested try except blocks in python a good ...
38,2015-11-06 10:04:38,How do I change the string representation of a...,<python><string><python-3.x><printing>,309,how change string representation python class,how change string representation python class,how do i change the string representation of a...
39,2024-02-13 18:27:19,Scraping: SSL: CERTIFICATE_VERIFY_FAILED error...,<python><web-scraping><beautifulsoup><scrapy><...,303,scraping ssl certificate verify failed error e...,scraping ssl certificate verify failed error e...,scraping : ssl : certificate verify failed err...
40,2017-10-01 15:04:38,Python: access class property from string,<python><syntax>,290,python access class property string,python access class property string,python : access class property from string
41,2022-07-30 13:07:53,How to count the frequency of the elements in ...,<python><list><frequency>,290,how count frequency elements unordered list,how count frequency element unordered list,how to count the frequency of the elements in ...
42,2022-03-01 03:37:01,Find first element in a sequence that matches ...,<python><predicate>,284,find first element sequence matches predicate,find first element sequence match predicate,find first element in a sequence that matches ...
43,2021-07-13 19:58:45,"Confused by python file mode ""w+""",<python><file><io>,277,confused python file mode,confused python file mode,confused by python file mode `` w ``
44,2022-05-01 16:39:08,Python import csv to list,<python><csv>,270,python import csv list,python import csv list,python import csv to list
45,2022-10-31 10:35:27,Compute list difference,<python><list>,264,compute list difference,compute list difference,compute list difference
46,2021-03-01 22:12:03,How do I pass a method as a parameter in Python,<python><parameter-passing>,262,how pass method parameter python,how pas method parameter python,how do i pass a method as a parameter in python
47,2022-12-12 17:00:15,How to reliably open a file in the same direct...,<python><directory>,260,how reliably open file directory currently run...,how reliably open file directory currently run...,how to reliably open a file in the same direct...
48,2021-02-09 11:47:31,ModuleNotFoundError: What does it mean __main_...,<python><module><python-3.6><python-import>,259,modulenotfounderror what mean main package,modulenotfounderror what mean main package,modulenotfounderror : what does it mean main i...
49,2023-01-06 18:48:48,ImportError: No module named matplotlib.pyplot,<python><matplotlib>,259,importerror module named matplotlib.pyplot,importerror module named matplotlib.pyplot,importerror : no module named matplotlib.pyplot

In [24]:
# Load pre-trained universal sentence encoder model
embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")

In [25]:
# Sentences for which you want to create embeddings,
# passed as an array in embed()
list_sentences = df_net['sentence_dl'].tolist()
print(list_sentences)
embeddings = embed(df_net['sentence_dl'])
# Convertir les embeddings en numpy array pour un traitement ultérieur
embeddings_np = embeddings.numpy()

# Printing embeddings of each sentence
print(embeddings_np)

['determine the type of an object ?', 'why can t python parse this json data ?', 'best way to convert string to bytes in python 3 ?', 'display number with leading zeros', 'create a pandas dataframe by appending one row at a time', 'should i use has key ( ) or in on python dicts ?', 'how to check if type of a variable is string ?', 'which exception should i raise on bad illegal argument combinations in python ?', 'using property versus getters and setters', 'how can i check if a string represents an int , without using try except ?', 'how can i use pickle to save a dict ( or any other python object ) ?', 'getting a map ( ) to return a list in python 3.x', 'how can i pivot a dataframe ?', 'determine if variable is defined in python', 'reading json from a file', 'python dictionary comprehension', "is there a way to perform `` if '' in python s lambda ?", 'convert a list of characters into a string', 'how to add to the pythonpath in windows , so it finds my modules packages ?', 'how to find list intersection ?', 'redirect stdout to a file in python ?', 'store output of subprocess.popen call in a string', 'why does range ( start , end ) not include end ?', 'convert a python dict to a string and back', 'how do you properly determine the current script directory ?', 'how can i check if a key exists in a dictionary ?', 'double iteration in list comprehension', 'what s the difference between ` raw input ( ) ` and ` input ( ) ` in python 3 ?', 'numpy array initialization ( fill with identical values )', 'python function global variables ?', 'get loop count inside a for loop', 'how do i convert all of the items in a list to floats ?', 'str object has no attribute decode . python 3 error ?', 'access multiple elements of list knowing their index', 'take the content of a list and append it to another list', 'list files only in the current directory', "error `` import error : no module named numpy '' on windows", 'are nested try except blocks in python a good programming practice ?', 'how do i change the string representation of a python class ?', 'scraping : ssl : certificate verify failed error for : en.wikipedia.org', 'python : access class property from string', 'how to count the frequency of the elements in an unordered list ?', 'find first element in a sequence that matches a predicate', 'confused by python file mode `` w ``', 'python import csv to list', 'compute list difference', 'how do i pass a method as a parameter in python', 'how to reliably open a file in the same directory as the currently running script', 'modulenotfounderror : what does it mean main is not a package ?', 'importerror : no module named matplotlib.pyplot']
[[ 0.00277021 -0.03878904 -0.02385746 ... -0.03576632  0.06212298
   0.04057778]
 [ 0.00848089 -0.06084437 -0.02827081 ...  0.07352952  0.00541463
  -0.03460141]
 [-0.04485909 -0.06419387 -0.00500961 ...  0.07943646  0.04332128
  -0.04379783]
 ...
 [-0.00076144  0.02856596 -0.04422116 ...  0.09356825  0.04622117
  -0.00504708]
 [-0.07062192 -0.03323411 -0.00845806 ...  0.03018114  0.04337119
  -0.01695   ]
 [-0.00676554  0.06106631 -0.03178125 ...  0.0798019  -0.02155649
  -0.04342897]]

In [26]:
# To print each embeddings along with its corresponding
# sentence below code can be used.
for i in range(len(list_sentences)):
    print(list_sentences[i])
    print(embeddings[i])

Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
 -6.58627674e-02  1.37295090e-02  8.47445428e-02  4.46116589e-02
  7.92699456e-02 -3.41255181e-02  3.91644426e-02  1.47339981e-02
 -1.00537911e-02 -5.93076274e-02  8.08746144e-02 -3.22772041e-02
 -1.09998221e-02  6.01404645e-02  4.96639684e-02  3.42592821e-02
  1.85573883e-02  7.81171545e-02  5.49696833e-02  3.50731388e-02
  3.70104983e-02  1.47254476e-02  2.32921522e-02 -7.36271217e-02
 -2.48164628e-02 -8.22465420e-02 -5.60705326e-02  1.18168816e-03
 -1.34689454e-03 -9.42719262e-03 -9.74360015e-03  3.38166915e-02
  1.48446122e-02 -3.72792892e-02 -1.32196757e-03 -6.85120188e-03
 -5.16786613e-02  1.55117391e-02  1.85492225e-02 -5.05275838e-02
 -4.90088798e-02 -8.36824700e-02  1.22648161e-02 -3.53459939e-02
 -2.81941406e-02 -7.48446658e-02  7.33984858e-02 -5.17900027e-02
 -6.03617355e-02 -5.92241734e-02  3.60750221e-02 -5.44160865e-02
 -2.76547261e-02 -5.88481277e-02 -7.58901983e-02  2.21602116e-02
  9.90563817e-03  4.46535274e-02 -4.04809276e-03  4.85982746e-02
 -5.15181683e-02  4.73576151e-02  8.26887712e-02 -1.32418666e-02
 -6.61578923e-02 -4.22662571e-02  8.59610457e-03  2.43478902e-02
 -3.32158804e-02 -2.09802184e-02 -5.10978960e-02 -3.65868062e-02
  2.47813649e-02 -4.48581539e-02 -5.99967055e-02  8.21179885e-04
  2.58036479e-02 -3.35494131e-02  1.29337851e-02  6.23132451e-04
 -8.45905021e-02  1.59870759e-02  2.99443379e-02 -2.20529623e-02
  4.15980741e-02 -4.08372283e-02 -1.17282532e-02  4.07223254e-02
  4.63472530e-02  7.88698345e-02 -1.36255007e-02  6.71376335e-03
 -3.57494433e-03  3.19045782e-02 -6.72474727e-02  8.23050737e-03
 -8.60774592e-02  3.85269448e-02  5.18420413e-02  1.35666681e-02
 -3.68549936e-02  4.72567230e-02  2.88375150e-02 -1.67425349e-02
 -6.06557615e-02 -3.11758239e-02  2.27786601e-02 -3.82510088e-02
  1.05486969e-02 -6.57118559e-02 -7.83916563e-02  6.32115230e-02
 -8.33168849e-02  4.83246259e-02 -6.27286211e-02  3.75317968e-02
  2.31580958e-02 -3.84137817e-02 -4.95733954e-02  4.28241603e-02
  2.27510631e-02 -2.81430669e-02 -6.88774977e-03 -4.99155931e-02
 -8.47376958e-02 -2.02504639e-02 -1.50863007e-02 -1.01050260e-02
 -9.94727202e-03  1.66442450e-02 -8.04435313e-02  1.32480757e-02
  4.93797734e-02 -2.34039370e-02  4.15724367e-02 -3.65977101e-02
  8.09249654e-02 -3.27641852e-02  2.00861003e-02  2.29013991e-02
  4.96060923e-02  4.72805696e-03  5.42538054e-02 -1.46909209e-04
 -8.94950330e-03 -6.58638775e-02  3.81702110e-02  6.43081814e-02
 -3.54062300e-03  4.64642160e-02 -3.11771054e-02 -6.32777857e-03
 -4.01009340e-03 -2.06128042e-02 -1.35089476e-02  2.34001093e-02
  6.25708774e-02 -2.48294920e-02 -7.17890933e-02  8.32280144e-03
 -2.78192684e-02  6.89253807e-02  3.87826413e-02  9.96588077e-03
 -4.98358756e-02 -2.37990860e-02  1.33511210e-02  1.97380502e-02
  1.74850561e-02 -9.82851814e-03  1.49728563e-02 -4.98145707e-02
  7.59121701e-02 -2.72109620e-02 -7.77486414e-02  4.87191118e-02
 -2.24910993e-02 -6.05096035e-02  1.83353070e-02  3.61740589e-02
 -2.57429909e-02  1.17054302e-02 -1.19475611e-02 -1.72793493e-02
 -7.34649077e-02  3.62674892e-02  4.15802486e-02  1.94151271e-02
 -3.76856104e-02  5.57897016e-02  1.13724172e-02 -5.85546382e-02
 -3.54250558e-02 -1.61418617e-02 -2.89409216e-02  8.34715664e-02
  3.99913788e-02  2.72400342e-02  4.16386873e-02  5.43528795e-02
  2.05512829e-02 -2.00390443e-02 -7.55461007e-02  2.53067408e-02
 -1.97113212e-03  4.55992483e-02 -5.35723753e-02  7.21477764e-03
  5.13029695e-02 -4.95323353e-02 -2.87407134e-02  3.54528576e-02
  6.34298101e-02 -7.98970908e-02  7.55390003e-02  3.07270307e-02
 -4.55999896e-02  8.61196313e-03 -3.25060934e-02 -6.53330609e-02
  8.41742754e-02 -2.51480285e-02  1.08223304e-03 -3.68540101e-02
  2.02605613e-02  4.94554229e-02  1.62302628e-02  9.48342145e-04
  2.45700032e-02 -1.42805530e-02  5.19557856e-02  6.79961741e-02
 -3.31426635e-02 -3.77434082e-02 -3.83313410e-02 -5.99847781e-03
  3.79104633e-03  3.41476202e-02 -6.15113974e-02 -2.53862552e-02
 -2.87768226e-02  2.64264606e-02  8.11399817e-02 -7.04952097e-03
  7.75999650e-02 -2.31667031e-02 -3.79562639e-02 -7.12672919e-02
  7.94366300e-02 -1.37347728e-02 -3.40325534e-02  6.38442263e-02
 -3.96322198e-02  7.23022148e-02  5.92533909e-02  4.16863114e-02
  1.08741643e-02 -3.85831185e-02 -4.41446118e-02  5.14940582e-02
 -5.11881486e-02  7.06167594e-02 -6.08116854e-03 -5.10371737e-02
 -3.90183292e-02  1.56941800e-03 -4.42803046e-03 -6.17772564e-02
 -2.70182230e-02  6.70208186e-02  4.86565940e-02 -4.87814769e-02
  7.16527328e-02  5.62517829e-02 -2.50276905e-02 -7.60985315e-02
 -2.55195629e-02  6.04959875e-02 -7.63613218e-03  2.85157338e-02], shape=(512,), dtype=float32)
create a pandas dataframe by appending one row at a time
tf.Tensor(
[-0.03590527 -0.07509366  0.05937348  0.00041371  0.02931273  0.01694298
 -0.06253327 -0.06162477 -0.04032623  0.06506876  0.05569078  0.06336444
 -0.05676568 -0.01752326 -0.01309765  0.07662923  0.04491867 -0.06652638
  0.03584677 -0.05003475 -0.05109149  0.0090717  -0.0171915   0.02989297
 -0.01132342 -0.01188074  0.03798521  0.00434482  0.00840312  0.00862818
  0.04764723  0.03809818  0.06693052 -0.02691011  0.0110851   0.01097395
 -0.04271194 -0.03463425 -0.02060637 -0.04745829  0.04943189 -0.03104585
 -0.0569724   0.02355502  0.07062426  0.02859504 -0.05341701  0.04699909
  0.02845447 -0.03788693  0.07324129  0.0673707   0.05669019  0.04947773
  0.02275501  0.03214756  0.03071344 -0.04750248  0.0054822  -0.02325946
 -0.04350599 -0.03524031 -0.05369963  0.05381002  0.00108459  0.03203174
  0.06731644 -0.00278953 -0.07460617  0.0580024  -0.04009672 -0.03842531
 -0.04475375  0.0745555   0.01741169  0.04132526  0.0761499   0.03596868
  0.05401644 -0.04488113  0.0554978   0.03309166  0.0141045  -0.02612758
  0.01906216 -0.02029047 -0.05697796 -0.04059166 -0.07298639  0.021344
 -0.02515009  0.04025069 -0.00826784  0.06920845 -0.05480422 -0.0019923
 -0.03230395  0.02644879  0.02284603 -0.07634799  0.06317297 -0.01348525
 -0.06612913 -0.07201537 -0.06145947 -0.04146791  0.00164675  0.01076189
 -0.00249288 -0.00780642 -0.02671839 -0.05055491 -0.02652425 -0.03968439
  0.03111605 -0.03316404 -0.04577072  0.02760028  0.00876755 -0.0588902
  0.03408037  0.03873993 -0.05924643  0.02117066 -0.00721104  0.03146239
  0.03440632 -0.01633522  0.07232047 -0.00370866  0.00663329 -0.00789435
 -0.04248482 -0.00506276 -0.02000947  0.03107944 -0.0476977  -0.03797037
 -0.00676467 -0.00669839 -0.00041593  0.03904812  0.07254148 -0.07180444
  0.02135212 -0.07537784  0.02543283  0.00672743 -0.00795854 -0.05638454
 -0.04841435  0.0348521   0.04876194 -0.00258255 -0.01930371  0.00080817
 -0.06563838 -0.07050478  0.03729003  0.04076984 -0.06536874 -0.04864258
  0.03743284  0.05502309 -0.04985477 -0.07534551 -0.00714553 -0.03538454
 -0.02442087 -0.00723773 -0.02729654  0.00837728  0.01395627 -0.00258739
 -0.01852075 -0.00924465 -0.03838173  0.07238205 -0.00283394  0.00268123
  0.05775175  0.02786272 -0.03521406 -0.02135787 -0.01953549  0.05874854
 -0.01804475  0.069731    0.03129256  0.07193942 -0.01215402  0.04211899
  0.00411243  0.00883613 -0.05413968  0.05814051  0.0537633   0.07662922
  0.06553335 -0.0046567  -0.03120345 -0.03043957 -0.07469532  0.02771872
 -0.05601388  0.01107212 -0.06140855 -0.02744863 -0.07564385  0.05256589
  0.004228    0.07630685  0.04060781  0.0119876  -0.0499431   0.0474346
 -0.05705436  0.04415138 -0.00407875 -0.06953095  0.07308238 -0.01561728
  0.04930067  0.03518314  0.04714908 -0.0664525   0.06230496 -0.06622118
  0.00634887 -0.04780488 -0.0190571  -0.05707558  0.01459006 -0.05109309
  0.07588068 -0.04394233  0.06843951  0.07593071  0.06000969  0.05168317
 -0.04291086 -0.04996778  0.02112062  0.02689707  0.0320137   0.02171806
 -0.03114481  0.05257932  0.01537468  0.06527981  0.06207739 -0.05111494
 -0.00920404 -0.07170091  0.01548848  0.02083973 -0.02449793 -0.07387683
  0.03307002 -0.00504767 -0.04304904  0.06996812  0.01125625 -0.01247106
 -0.01203325  0.03313898  0.03177935 -0.07432641 -0.04186225 -0.03557896
 -0.05721359  0.02139512  0.06231609 -0.0001559  -0.01510337  0.06620722
  0.00167573  0.04248647  0.07649105  0.02660428  0.06693569 -0.01969829
  0.03281637 -0.0261378   0.00667856 -0.07516681  0.01060873  0.03818677
  0.04198661 -0.041921    0.03908834  0.02406907  0.04693214  0.00947023
  0.07429188  0.0386868   0.03499305  0.00453066 -0.07570925  0.02172964
 -0.02123083 -0.03521191  0.00649737 -0.04795069 -0.01338889 -0.03552453
 -0.00886374  0.05778334  0.02844339  0.02074428 -0.03745488  0.01685596
  0.02981161  0.03425949 -0.05700664 -0.07137607  0.0199511   0.00998753
  0.04416413  0.06642701 -0.0119275  -0.03560473 -0.04642482 -0.0328176
  0.03224     0.04717992 -0.00942486  0.01048911  0.00831121  0.06434784
 -0.0064233   0.051641    0.06872269  0.02831403 -0.01835822  0.07469901
 -0.06592362 -0.03280508  0.04870756  0.07441761 -0.01071902 -0.04472244
  0.06537682 -0.06098359 -0.07662881  0.01570523  0.00375225 -0.06632904
 -0.02037911 -0.04702833  0.00146985  0.02291722  0.02380338 -0.05456195
 -0.01825586 -0.06846534 -0.07648506  0.0263745  -0.02683752 -0.02755322
 -0.05913635  0.01210206 -0.07661428  0.03233914  0.05367138  0.01941352
 -0.00621037 -0.01586464  0.0701974   0.07378994 -0.06338455 -0.05556023
  0.05778227  0.07003158 -0.00308955 -0.04890985  0.02519138 -0.03325297
  0.02978319 -0.02007148  0.07293011  0.04315107  0.06918218  0.03176973
 -0.053374    0.00445011  0.03861337  0.03836099 -0.02886618 -0.06794962
 -0.0512842  -0.06056005 -0.0443377   0.01964907 -0.07168771  0.069586
  0.01371663  0.02404675 -0.02797298  0.02451998  0.06099162 -0.05008875
 -0.04769169  0.06949755  0.04049984  0.03055282 -0.07147872 -0.05182819
 -0.02303643  0.0056246   0.00699728 -0.01122491 -0.02509752  0.0696004
 -0.02635004 -0.0660968   0.05615596  0.00747071  0.01347244  0.03860902
  0.03732661 -0.03356796 -0.03470063  0.06307061 -0.04504599  0.0681352
 -0.05685077  0.06626614 -0.07586116  0.05420283  0.04555371 -0.04496501
 -0.03770811  0.03238181 -0.05923833  0.04538332 -0.04162923 -0.00114623
 -0.04128467 -0.05972518 -0.00517234 -0.04479493  0.02728984 -0.04129935
 -0.01091166  0.00110755  0.04621144 -0.01828778 -0.01999868  0.02551452
 -0.00625141  0.07343569  0.07657477  0.06415749  0.02727356 -0.07331564
 -0.06953223  0.03570815  0.00025961 -0.05850599  0.06864779  0.06405532
  0.01802888  0.0741502  -0.01928405 -0.03321729 -0.04153637 -0.04963901
  0.03350923  0.01764152  0.0316231   0.03496422  0.07635113 -0.06218574
  0.00177521  0.03463439  0.00994772 -0.03983643 -0.00407622 -0.07239806
  0.03780439  0.01751144  0.03883687  0.07170909  0.02958927  0.01404872
  0.05234536 -0.04007334  0.05633965 -0.05803158  0.00255863  0.05788484
 -0.03569043  0.06430703  0.01007558  0.04783826  0.03618659  0.02368589
  0.00992252 -0.01587025 -0.02560276 -0.00100978 -0.00447226 -0.00234163
  0.036663   -0.00570278 -0.06521305 -0.06299319  0.03530723  0.07634411
  0.0190436  -0.02226122], shape=(512,), dtype=float32)
should i use has key ( ) or in on python dicts ?
tf.Tensor(
[-1.69402175e-02 -5.21979071e-02  4.64632213e-02 -2.74528656e-02
  4.18753736e-02 -4.75950213e-03 -4.25585471e-02 -5.62764890e-02
  3.87215354e-02  4.12969366e-02  2.87964251e-02  7.53747225e-02
 -4.11456712e-02  5.84244467e-02  2.83196364e-02  8.34677890e-02
  5.51679954e-02 -3.23043764e-02  4.77955304e-02 -3.31133939e-02
  7.16633350e-02  1.80637930e-02 -6.73884572e-03  5.87063981e-03
 -7.69155398e-02 -2.59246975e-02  4.66592163e-02 -3.37660201e-02
 -1.94201916e-02 -2.35061683e-02  2.14445181e-02  3.93680371e-02
 -5.50189661e-03 -5.87774180e-02 -3.03925369e-02 -7.15616941e-02
 -1.23800179e-02  9.61706880e-03 -2.45651007e-02  3.55675556e-02
  7.71454424e-02 -4.35989834e-02  3.98878707e-03  2.78669745e-02
  4.28139195e-02  4.45913076e-02 -1.34880058e-02 -5.52582629e-02
  8.21528286e-02  2.24525165e-02  6.15041927e-02  8.20322335e-02
  7.38762990e-02 -3.55958454e-02 -3.20461802e-02 -5.80404922e-02
 -5.44955768e-02  4.03184593e-02 -5.49485944e-02 -6.89386157e-03
 -5.22876345e-02  6.73936214e-03 -4.18568924e-02 -6.86236471e-02
  2.73925960e-02  6.51859343e-02 -4.99739386e-02 -9.77292284e-03
 -7.17353523e-02  1.71350315e-02 -5.59555851e-02  2.08660811e-02
 -4.06402685e-02  4.44092005e-02  1.31771434e-02 -1.78018436e-02
 -1.70854181e-02 -3.80994119e-02  1.45215373e-02  6.37867451e-02
  3.14678694e-03  2.86633503e-02  2.47817691e-02 -2.26341039e-02
  7.58840442e-02  3.44541818e-02  2.82140858e-02 -6.20829053e-02
 -2.65546348e-02 -7.41272420e-02  1.21945292e-02 -4.82071042e-02
 -8.06165412e-02  5.49924970e-02 -7.24401027e-02  9.09257680e-03
 -2.72625368e-02 -2.59298105e-02 -8.43231007e-03 -8.19511786e-02
 -2.87587824e-03 -2.19161250e-02  8.29755291e-02  1.33183633e-03
 -2.73941606e-02 -1.83880553e-02  3.94664146e-02  2.05527022e-02
 -1.08973263e-02  2.98844092e-02  2.98722163e-02  6.34207809e-03
 -6.59680218e-02  3.32248211e-02  1.63192712e-02  1.49768870e-03
  1.12199951e-02  4.98231538e-02 -7.20457211e-02 -4.66556214e-02
  3.95496637e-02  1.49505371e-02 -2.11392529e-02 -7.28571489e-02
 -2.48078723e-02 -3.90036069e-02 -1.68108772e-02  8.42483807e-03
  5.77286258e-02  1.38037102e-02  1.58326663e-02  5.96047752e-02
 -2.15364117e-02 -3.90674733e-02  4.35414091e-02 -6.81550615e-03
  2.61863274e-03  3.28772329e-02  2.35059205e-02 -4.28387597e-02
 -3.42305675e-02 -3.50574628e-02 -2.34486982e-02 -4.86408547e-02
  4.18963917e-02 -8.26448575e-02  3.92039381e-02 -1.37007665e-02
 -2.88133081e-02 -4.98721711e-02  2.63998024e-02 -6.76363632e-02
 -6.73627779e-02  6.37763645e-03  1.46020635e-03  8.88925605e-03
  3.51565368e-02 -3.88340317e-02  3.15070078e-02 -2.18067318e-02
 -3.91309150e-02  7.22374534e-03 -3.17997113e-02 -4.85099033e-02
  1.32586267e-02  1.65601745e-02 -4.39560525e-02  2.64807232e-02
 -3.31419073e-02  4.40073805e-03 -9.75616463e-03  2.65078750e-02
  1.12505751e-02  2.36125793e-02 -7.46519566e-02 -2.03852449e-02
 -1.80908275e-04  1.81718580e-02 -1.03552220e-02 -2.56939442e-03
  6.18446954e-02  4.41305945e-03 -4.85797822e-02  5.52812479e-02
 -3.97524564e-03  5.25182523e-02 -6.41418025e-02  7.06077963e-02
 -2.33164951e-02  5.66726215e-02  7.99591020e-02  1.95067525e-02
  6.41750768e-02 -5.16166128e-02 -2.42228154e-02  6.91563189e-02
  2.62549464e-02  8.32799897e-02  6.99793696e-02 -3.08081452e-02
 -1.47971818e-02  3.36258821e-02 -8.28680992e-02  7.71241710e-02
  3.40969525e-02 -1.30352965e-02  2.87386179e-02  8.11932832e-02
 -7.92694166e-02 -3.61740962e-02 -7.13298693e-02  8.31148699e-02
  1.72447674e-02 -2.47089881e-02  1.84651464e-02 -3.31571214e-02
 -5.73583990e-02  5.95125630e-02 -7.34040290e-02  1.27316182e-02
  6.88519776e-02  2.27159020e-02  3.84147204e-02  6.49872348e-02
  6.09264337e-02  3.23598310e-02  2.99096145e-02  7.45799392e-02
  1.87719055e-02 -1.33967604e-02 -4.73915040e-02 -3.46780457e-02
 -3.62525918e-02 -3.08311041e-02  3.34605724e-02  6.52451394e-03
  6.74978420e-02 -3.37176141e-03  4.39158008e-02 -4.37719785e-02
 -5.15446365e-02 -1.88799873e-02 -5.94729632e-02  5.55307418e-02
  2.21232465e-03  2.26193890e-02  1.81692131e-02 -2.00278200e-02
 -8.18645433e-02  7.03283697e-02 -6.89894781e-02 -4.59652441e-03
 -5.00554964e-03  4.49247397e-02 -7.91010410e-02 -2.01847106e-02
  1.38193853e-02 -6.35889992e-02  3.03868800e-02  3.10383383e-02
 -4.04021814e-02  3.15215252e-02  5.51843531e-02 -3.85368466e-02
  1.14138040e-03  4.81316485e-02  7.96957389e-02 -1.90578436e-03
 -3.68009247e-02  7.59127922e-03 -6.26392066e-02  2.19684802e-02
  7.43616745e-02 -1.53753087e-02  4.94939573e-02  5.13500310e-02
 -1.85973775e-02  6.55764043e-02  8.04851279e-02 -2.84502096e-02
 -4.89387065e-02  6.88332692e-02 -1.37193482e-02 -4.62514907e-02
  1.07204784e-02 -7.91175216e-02  1.34995077e-02  7.46545643e-02
  3.11669465e-02  1.26468964e-04 -4.00496647e-02  5.54024652e-02
  7.95257539e-02  2.02334281e-02  7.75914937e-02 -4.40268032e-03
 -3.20674330e-02  4.71505113e-02 -8.31047818e-02  6.82657734e-02
 -4.53991927e-02 -3.94160440e-03 -7.79506704e-03  7.60704698e-03
 -7.96167925e-02 -2.65475828e-03  3.53693180e-02  7.85043240e-02
 -2.62055523e-03 -5.46475239e-02 -1.81572661e-02  4.49091233e-02
  3.24352458e-03  3.80817652e-02 -1.52828800e-03 -5.68101928e-02
  4.34290543e-02  1.81842523e-04 -1.03304312e-02  8.05723742e-02
  7.36249087e-04 -4.56353202e-02  1.65274758e-02 -1.74584407e-02
  4.86934707e-02 -1.47107057e-02  2.96327509e-02  1.29739875e-02
  5.07405698e-02  6.07413724e-02 -2.71034986e-02  5.61419353e-02
  6.39542937e-02  7.31993392e-02  1.03445733e-02 -8.26231577e-03
 -7.81654045e-02  1.06332293e-02  4.24388908e-02 -3.85920182e-02
 -3.81370112e-02 -1.61675143e-03  4.92465682e-02  6.44789189e-02
 -8.33791047e-02 -5.61257638e-02  2.40574405e-03  1.99845452e-02
 -4.01641317e-02 -5.63226417e-02  7.78245274e-03  2.65132822e-02
  3.91168706e-02  2.89011281e-03 -4.66416217e-02 -3.88381071e-02
 -8.29630792e-02  8.22823644e-02 -5.50469868e-02  3.05653196e-02
  1.64445229e-02  1.57855339e-02 -5.93259931e-02 -4.38507274e-02
  4.49574590e-02 -1.00217136e-02 -6.09868988e-02  4.32875417e-02
  3.58280167e-02 -5.04620746e-02 -3.14829946e-02 -3.23155262e-02
 -4.83908653e-02  5.70864007e-02 -5.92233650e-02 -6.89480826e-02
 -9.19110607e-03  1.30997887e-02 -4.10978459e-02 -7.60651827e-02
 -2.64630299e-02  2.27510482e-02 -2.46608332e-02  4.67521772e-02
 -6.59026951e-02  2.29926556e-02  7.56643638e-02  4.73884940e-02
 -3.13132582e-03 -2.59821024e-03 -2.64774375e-02  2.16053687e-02
 -5.36578670e-02  3.85626666e-02 -6.13076799e-02  3.73627171e-02
  2.51410343e-03 -2.32845694e-02 -4.91025075e-02  2.90016644e-02
  4.46287282e-02  5.94999865e-02 -4.78180498e-03  8.31382945e-02
 -1.52241876e-02  4.08261754e-02 -5.75913638e-02 -4.44616713e-02
 -9.90684982e-03  1.97569355e-02  4.99984175e-02  5.59839010e-02
 -4.32932451e-02  6.99316636e-02 -2.21610218e-02 -1.84357017e-02
 -2.70966832e-02  4.40366082e-02  2.83495840e-02  6.25346005e-02
  4.23125364e-03 -4.44635972e-02 -2.07432043e-02  8.16721544e-02
  4.26349156e-02  2.54363045e-02 -3.07903101e-04  2.23578736e-02
 -7.73908496e-02  1.64060928e-02  1.45251835e-02  5.47806434e-02
  2.93257106e-02  1.14898896e-03  1.54308733e-02  6.47981390e-02
 -6.57409281e-02  2.65473817e-02  2.85752602e-02 -7.88366378e-05
  1.02318078e-03 -6.60317838e-02  8.29920825e-03  4.71405499e-02
  3.05374842e-02 -3.93930310e-03  4.34129275e-02 -2.04367042e-02
  5.65737002e-02 -4.67473939e-02 -5.59364408e-02  5.10172099e-02
  8.23488161e-02  4.83327769e-02  1.12641379e-02 -7.58780614e-02
 -2.99072042e-02  5.44145368e-02  9.22037847e-03  4.74162810e-02
  2.93028411e-02  3.45374793e-02  2.87905131e-02 -4.49463949e-02
 -7.83601485e-04  2.82993820e-03 -3.31942365e-02 -7.30586797e-02
  2.60779192e-03  6.48247674e-02 -2.16518380e-02  3.76522653e-02
  8.34343582e-02 -4.27656732e-02  1.30138546e-02  4.68953960e-02
  2.74333116e-02  1.08621661e-02  3.67804989e-02 -2.24923864e-02
 -5.18306298e-03 -6.49298206e-02  4.58240211e-02 -4.23769541e-02
 -3.37922499e-02  3.83243524e-02 -5.98066151e-02 -3.51074524e-02
  2.80334763e-02 -8.19388628e-02  2.30169971e-03 -2.14541201e-02
 -7.11845160e-02 -2.42874715e-02  4.14073244e-02 -4.81506512e-02
 -4.17628586e-02 -3.86674097e-03  9.62382741e-03  3.87785919e-02
  4.50039096e-02 -6.38626814e-02  3.57156433e-02  6.26635626e-02
 -4.82224999e-03  3.95458518e-03  5.65531775e-02 -4.23054993e-02
 -2.22854186e-02  7.75334090e-02 -2.52589826e-02 -1.71185825e-02], shape=(512,), dtype=float32)
how to check if type of a variable is string ?
tf.Tensor(
[ 3.71742286e-02 -8.25563967e-02  2.13222741e-03  6.74513280e-02
 -3.90680786e-03  5.87820262e-02  3.62106375e-02 -5.22611365e-02
  3.83948088e-02  8.31566378e-02  1.73614733e-02  5.08744307e-02
  4.26895879e-02  8.63535181e-02  8.41124542e-03  9.41641629e-02
  1.24564134e-02  7.56884813e-02  6.86071068e-02 -1.93798356e-03
  7.77773038e-02  1.25191966e-03  2.38659885e-02  3.61949578e-02
 -4.71273363e-02  2.53382437e-02  2.34803148e-02 -3.56096774e-02
  5.99839985e-02  9.50252265e-03 -3.04530673e-02 -4.11508046e-03

In [27]:
tags = [tag[1:len(tag) - 1].split('><') for tag in df_net['Tags']]
tags

[['python', 'dictionary', 'types', 'typeof'],
 ['python', 'json', 'parsing'],
 ['python', 'string', 'character-encoding', 'python-3.x'],
 ['python', 'integer', 'string-formatting'],
 ['python', 'pandas', 'dataframe', 'append'],
 ['python', 'dictionary'],
 ['python', 'string', 'variables', 'types'],
 ['python', 'exception', 'arguments'],
 ['python', 'properties', 'getter-setter'],
 ['python', 'string', 'integer'],
 ['python', 'dictionary', 'pickle'],
 ['python', 'list', 'python-3.x', 'map-function'],
 ['python', 'pandas', 'group-by', 'pivot', 'pivot-table'],
 ['python', 'variables', 'defined'],
 ['python', 'json'],
 ['python', 'dictionary', 'list-comprehension'],
 ['python', 'lambda', 'conditional-operator'],
 ['python', 'string'],
 ['python', 'windows', 'environment-variables', 'pythonpath'],
 ['python', 'arrays', 'intersection'],
 ['python', 'stdout'],
 ['python', 'subprocess'],
 ['python', 'range'],
 ['python', 'json', 'dictionary', 'serialization'],
 ['python', 'path', 'working-directory'],
 ['python'],
 ['python', 'list-comprehension'],
 ['python', 'python-3.x', 'input'],
 ['python', 'arrays', 'numpy'],
 ['python', 'global-variables'],
 ['python', 'for-loop'],
 ['python', 'list', 'casting'],
 ['python', 'python-3.x'],
 ['python', 'python-3.x', 'list', 'indexing', 'element'],
 ['python', 'list'],
 ['python'],
 ['python', 'python-3.x', 'numpy', 'import', 'scipy'],
 ['python'],
 ['python', 'string', 'python-3.x', 'printing'],
 ['python', 'web-scraping', 'beautifulsoup', 'scrapy', 'ssl-certificate'],
 ['python', 'syntax'],
 ['python', 'list', 'frequency'],
 ['python', 'predicate'],
 ['python', 'file', 'io'],
 ['python', 'csv'],
 ['python', 'list'],
 ['python', 'parameter-passing'],
 ['python', 'directory'],
 ['python', 'module', 'python-3.6', 'python-import'],
 ['python', 'matplotlib']]

In [28]:
# Utilisation de MultiLabelBinarizer pour créer des étiquettes binaires
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
labels = mlb.fit_transform(tags)
labels

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [29]:
# Séparation des données en ensembles d'entraînement et de test
from sklearn.model_selection import train_test_split

train_title, test_title, train_labels, test_labels = train_test_split(embeddings_np, labels, test_size=0.2, random_state=42)
print("train_title shape : {}".format(train_title.shape))
print("test_title shape : {}".format(test_title.shape))
print("train_labels shape : {}".format(train_labels.shape))
print("test_labels shape : {}".format(test_labels.shape))

train_title shape : (40, 512)
test_title shape : (10, 512)
train_labels shape : (40, 66)
test_labels shape : (10, 66)

In [30]:
# Initialize Logistic Regression with OneVsRest
param_logit = {"estimator__C": [100, 10, 1.0, 0.1],
               "estimator__penalty": ["l1", "l2"],
               "estimator__dual": [False],
               "estimator__solver": ["liblinear"]}

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.multiclass import OneVsRestClassifier

lr = GridSearchCV(OneVsRestClassifier(LogisticRegression()),
                              param_grid=param_logit,
                              n_jobs=-1,
                              cv=5,
                              scoring="f1_weighted",
                              return_train_score = True,
                              refit=True)
lr.fit(train_title, train_labels)

# Predict
test_labels_predicted = lr.predict(test_title)

# Inverse transform
test_labels_pred_inversed = mlb\
    .inverse_transform(test_labels_predicted)
test_labels_inversed = mlb\
    .inverse_transform(test_labels)

print("Les 10 premiers tags prédits - vrais tags :")
print("Prédits:", test_labels_pred_inversed[0:10])
print("Vrais:", test_labels_inversed[0:10])

/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/fork_exec.py:38: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = os.fork()
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 3 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 9 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 16 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 25 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 33 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label 45 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 46 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 48 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 52 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 54 is present in all training examples.
  warnings.warn(

Les 10 premiers tags prédits - vrais tags :
Prédits: [('python',), ('python',), ('python',), ('list', 'python'), ('python',), ('python',), ('list', 'python', 'python-3.x'), ('python',), ('python',), ('list', 'python')]
Vrais: [('defined', 'python', 'variables'), ('beautifulsoup', 'python', 'scrapy', 'ssl-certificate', 'web-scraping'), ('for-loop', 'python'), ('list', 'python'), ('python', 'string'), ('module', 'python', 'python-3.6', 'python-import'), ('list-comprehension', 'python'), ('python',), ('python', 'python-3.x'), ('arrays', 'intersection', 'python')]

/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 63 is present in all training examples.
  warnings.warn(

In [31]:
from sklearn.metrics import coverage_error
from sklearn.metrics import label_ranking_average_precision_score
from sklearn.metrics import label_ranking_loss


def metrics_score(model, df, y_true, y_pred):
    """Compilation function of metrics specific to multi-label
    classification problems in a Pandas DataFrame.
    This dataFrame will have 1 row per metric
    and 1 column per model tested.

    Exemples de Metriques
    ----------------------------------------
    coverage_error = 3 : En moyenne, il faut inclure trois prédictions pour capturer toutes les étiquettes pertinentes pour chaque instance.
    label_ranking_average_precision_score = 0.85 : La précision moyenne des classements est de 85%. Cela signifie que la majorité des étiquettes pertinentes sont bien classées en haut.
    label_ranking_loss = 0.1 : Il y a 10% d'inversions dans les classements où les étiquettes non pertinentes sont classées avant les étiquettes pertinentes.

    Parameters
    ----------------------------------------
    model : string
        Name of the tested model
    df : DataFrame
        DataFrame to extend.
        If None : Create DataFrame.
    y_true : array
        Array of true values to test
    y_pred : array
        Array of predicted values to test
    ----------------------------------------
    """
    if(df is not None):
        df_results = df
    else:
        df_results = pd.DataFrame(index=["coverage_error", "label_ranking_average_precision_score",
                                       "label_ranking_loss"],
                               columns=[model])

    scores = []
    scores.append(coverage_error(y_true,
                                         y_pred))
    scores.append(label_ranking_average_precision_score(y_pred,
                                   y_true))
    scores.append(label_ranking_loss(y_true,
                                       y_pred))

    df_results[model] = scores

    return df_results

In [32]:
import sklearn.metrics as metrics
df_metrics_compare_use = metrics_score("Logit",
                                   df=None,
                                   y_true = test_labels,
                                   y_pred = test_labels_predicted)
df_metrics_compare_use

                                           Logit
coverage_error                         53.100000
label_ranking_average_precision_score   0.466212
label_ranking_loss                      0.490425

- coverage_error = 53.1 : Le modèle nécessite de parcourir un grand nombre de prédictions pour couvrir toutes les étiquettes pertinentes (53/66).
- label_ranking_average_precision_score = 0.466212 : La précision moyenne des classements des étiquettes est faible.
- label_ranking_loss = 0.490425 : Il y a 49% d'inversions dans les classements des étiquettes. C'est élevé.

Ce modèle donne des résultats meilleurs que BERT et Word2Vec mais cela reste faible.

In [37]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

# Initialiser le classificateur RandomForest
rf_model = RandomForestClassifier(random_state=42)
print("rf_model:", rf_model)

# Utiliser MultiOutputClassifier pour le modèle multi-label
rf_multioutput = OneVsRestClassifier(rf_model)
print("rf_multioutput:", rf_multioutput)

# Définir les hyperparamètres pour RandomizedSearchCV
param_rf = {
    "estimator__n_estimators": [50, 100, 200],
    "estimator__max_depth": [5,6,7],
    "estimator__min_samples_split": [2, 5, 10]
}

random_rf = RandomizedSearchCV(rf_multioutput, param_distributions=param_rf, cv=5, scoring='f1_weighted', n_jobs=-1)
random_rf.fit(train_title, train_labels)

# Meilleurs hyperparamètres
print("Meilleurs hyperparamètres trouvés par GridSearchCV:")
print(random_rf.best_params_)

# Prédictions avec le modèle optimisé
pred_labels = random_rf.predict(test_title)

# Inverse transform des prédictions optimisées
test_labels_pred_inversed_optimized = mlb.inverse_transform(pred_labels)
test_labels_inversed = mlb.inverse_transform(test_labels)

# Évaluer les performances avec le modèle optimisé
print("Les 10 premiers tags prédits avec le modèle optimisé - vrais tags :")
print("Prédits:", test_labels_pred_inversed_optimized[0:10])
print("Vrais:", test_labels_inversed[0:10])

df_metrics_compare_use_rf = metrics_score("Random Forest",
                                   df=None,
                                   y_true = test_labels,
                                   y_pred = pred_labels)

df_metrics_compare_use_rf

rf_model: RandomForestClassifier(random_state=42)
rf_multioutput: OneVsRestClassifier(estimator=RandomForestClassifier(random_state=42))

/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/fork_exec.py:38: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = os.fork()
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 3 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 9 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 16 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 25 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 33 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label 45 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 46 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 48 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 52 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 54 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:77: UserWarning: Label not 63 is present in all training examples.
  warnings.warn(

Meilleurs hyperparamètres trouvés par GridSearchCV:
{'estimator__n_estimators': 50, 'estimator__min_samples_split': 5, 'estimator__max_depth': 5}
Les 10 premiers tags prédits avec le modèle optimisé - vrais tags :
Prédits: [('python',), ('python',), ('python',), ('python',), ('python',), ('python',), ('python',), ('python',), ('python',), ('python',)]
Vrais: [('defined', 'python', 'variables'), ('beautifulsoup', 'python', 'scrapy', 'ssl-certificate', 'web-scraping'), ('for-loop', 'python'), ('list', 'python'), ('python', 'string'), ('module', 'python', 'python-3.6', 'python-import'), ('list-comprehension', 'python'), ('python',), ('python', 'python-3.x'), ('arrays', 'intersection', 'python')]

                                       Random Forest
coverage_error                             59.500000
label_ranking_average_precision_score       0.461667
label_ranking_loss                          0.538333

In [38]:
from sklearn.ensemble import GradientBoostingClassifier

# Initialiser le classificateur GradientBoostingClassifier
gb_model = GradientBoostingClassifier(random_state=42)
gb_multioutput = OneVsRestClassifier(gb_model, n_jobs=-1)

# Entraînement du modèle
gb_multioutput.fit(train_title, train_labels)
print("Modèle entraîné.")

# Prédictions
pred_labels = gb_multioutput.predict(test_title)

# Inverse transform des prédictions
test_labels_pred_inversed = mlb.inverse_transform(pred_labels)
test_labels_inversed = mlb.inverse_transform(test_labels)

# Évaluer les performances avec le modèle optimisé
print("Les 10 premiers tags prédits avec le modèle optimisé - vrais tags :")
print("Prédits:", test_labels_pred_inversed_optimized[0:10])
print("Vrais:", test_labels_inversed[0:10])


df_metrics_compare_use_gb = metrics_score("Gradient Boosting",
                                   df=None,
                                   y_true = test_labels,
                                   y_pred = pred_labels)
df_metrics_compare_use_gb

Modèle entraîné.
Les 10 premiers tags prédits avec le modèle optimisé - vrais tags :
Prédits: [('python',), ('python',), ('python',), ('python',), ('python',), ('python',), ('python',), ('python',), ('python',), ('python',)]
Vrais: [('defined', 'python', 'variables'), ('beautifulsoup', 'python', 'scrapy', 'ssl-certificate', 'web-scraping'), ('for-loop', 'python'), ('list', 'python'), ('python', 'string'), ('module', 'python', 'python-3.6', 'python-import'), ('list-comprehension', 'python'), ('python',), ('python', 'python-3.x'), ('arrays', 'intersection', 'python')]

                                       Gradient Boosting
coverage_error                                 53.100000
label_ranking_average_precision_score           0.457879
label_ranking_loss                              0.490677

In [39]:
pd.concat([df_metrics_compare_use, df_metrics_compare_use_rf, df_metrics_compare_use_gb], axis=1)

,Logit,Random Forest,Gradient Boosting
coverage_error,53.100000,59.500000,53.100000
label_ranking_average_precision_score,0.466212,0.461667,0.457879
label_ranking_loss,0.490425,0.538333,0.490677

Je décide de travailler avec la Régression Logistique qui me donne les meilleurs résultats.